project:
  type: website
  output-dir: docs
  render:
      - "*.qmd"
      - "!conda_env/"

website:
  title: "CS 1671 / CS 2071 / ISSP 2071 Human Language Technologies, Spring 2026"
  navbar:
    left:
      - href: project.qmd
        text: Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



